In [2]:
import numpy as np

# Task 1

In [3]:
class minHeap:
  def __init__(self, capacity):
    self.__capacity = capacity
    self.__hp = np.zeros(self.__capacity,dtype = int)
    self.__size = 0

  def insert(self, elem):
    self.__size += 1
    self.__hp[self.__size -1] = elem
    self.swim(self.__size -1)

  def swim(self, idx):
    pidx = (idx -1) // 2
    if idx > 0 and self.__hp[idx] < self.__hp[pidx]:
      self.__hp[idx], self.__hp[pidx] = self.__hp[pidx], self.__hp[idx]
      self.swim(pidx)

  def extractMin(self):
    root = self.__hp[0]
    self.__hp[0],self.__hp[self.__size-1] = self.__hp[self.__size-1], self.__hp[0]
    self.__size -= 1
    self.sink(0)
    return root

  def sink(self,idx):
    min = idx
    l = 2 * idx + 1
    r = 2 * idx + 2
    if r < self.__size and self.__hp[r] < self.__hp[min]:
      min = r
    if l < self.__size and self.__hp[l] < self.__hp[min]:
      min = l
    if min != idx:
      self.__hp[min],self.__hp[idx] = self.__hp[idx],self.__hp[min]
      self.sink(min)

  def sort(self):
    self._heapify()
    size1 = self.__size
    while self.__size > 1:
      self.extractMin()
    self.__size = size1

  def _heapify(self):
    for i in range(self.__size // 2 - 1, -1, -1):
      self.sink(i)


  def __str__(self):
    return str(self.__hp[:self.__size])

In [ ]:
heap = minHeap(5)
heap.insert(4)
heap.insert(3)
heap.insert(1)
heap.insert(5)
heap.insert(2)
print(heap)
heap.extractMin()
print(heap)
heap.sort()
print(heap)

[1 2 3 5 4]
[2 4 3 5]
[5 4 3 2]


# Task 2


In [4]:
class maxHeap:
  def __init__(self, capacity):
    self.__capacity = capacity
    self.__hp = np.zeros(self.__capacity,dtype = int)
    self.__size = 0

  def insert(self, elem):
    self.__size += 1
    self.__hp[self.__size -1] = elem
    self.swim(self.__size -1)

  def swim(self, idx):
    pidx = (idx -1) // 2
    if idx > 0 and self.__hp[idx] > self.__hp[pidx]:
      self.__hp[idx], self.__hp[pidx] = self.__hp[pidx], self.__hp[idx]
      self.swim(pidx)

  def extractMax(self):
    root = self.__hp[0]
    self.__hp[0],self.__hp[self.__size-1] = self.__hp[self.__size-1], self.__hp[0]
    self.__size -= 1
    self.sink(0)
    return root

  def sink(self,idx):
    min = idx
    l = 2 * idx + 1
    r = 2 * idx + 2
    if l < self.__size and self.__hp[l] > self.__hp[min]:
      min = l
    if r < self.__size and self.__hp[r] > self.__hp[min]:
      min = r
    if min != idx:
      self.__hp[min],self.__hp[idx] = self.__hp[idx],self.__hp[min]
      self.sink(min)

  def sort(self):
    self._heapify()
    size1 = self.__size
    while self.__size > 1:
      self.extractMax()
    self.__size = size1

  def _heapify(self):
    for i in range(self.__size // 2 - 1, -1, -1):
      self.sink(i)


  def __str__(self):
    return str(self.__hp[:self.__size])

In [ ]:
heap2 = maxHeap(5)
heap2.insert(4)
heap2.insert(3)
heap2.insert(1)
heap2.insert(5)
heap2.insert(2)
print(heap2)
heap2.extractMax()
print(heap2)
heap2.sort()
print(heap2)

[5 4 1 3 2]
[4 3 1 2]
[1 2 3 4]


# Task 3

In [5]:
def processTime(m, arr):
  heap3 = minHeap(m)
  for i in range(m):
    heap3.insert(0)
  for i in arr:
    heap3.insert(heap3.extractMin() + i)
  print(heap3)

processTime(4, [2, 4, 7, 1, 6])

[2 4 7 7]


# Task 4

In [ ]:
def topLargest(arr, k):
  heap4 = maxHeap(len(arr))
  for i in arr:
    heap4.insert(i)
  arr1 = np.zeros(k,dtype = int)
  for i in range(k):
    arr1[i] = heap4.extractMax()
  return arr1

print(topLargest([4, 10, 2, 8, 6, 7], 3))

[10  8  7]
