In [6]:
import numpy as np
class MinHeap:
  def __init__(self, cap):
    self.__cap = cap
    self.__arr = np.zeros(cap, int)
    self.__size = 0
  def insert(self, val):
    if self.__size >= self.__cap:
      print('Heap is full. Cannot insert')
      return
    self.__arr[self.__size] = val
    self.__size += 1
    self.swim()
  def swim(self):
    idx = self.__size - 1
    while self.__arr[idx] < self.__arr[idx-2//2] and idx > 0:
      self.__arr[idx], self.__arr[idx-2//2] = self.__arr[idx-2//2], self.__arr[idx]
      idx = idx-2//2
  def printHeap(self):
    print(self.__arr)
  def extractMin(self):
    if self.__size == 0:
      print('Heap is empty')
      return
    min = self.__arr[0]
    self.__arr[0], self.__arr[self.__size-1] = self.__arr[self.__size-1], self.__arr[0]
    self.__size -= 1
    self.sink(0)
    return min
  def sink(self, idx):
    min = idx
    l = 2*idx + 1
    r = 2*idx + 2
    if r < self.__size and self.__arr[r] < self.__arr[min]:
      min = r
    if l < self.__size and self.__arr[l] < self.__arr[min]:
      min = l
    if min != idx:
      self.__arr[min], self.__arr[idx] = self.__arr[idx], self.__arr[min]
      self.sink(min)
  def sort(self):
    self.heapify()
    size = self.__size
    while self.__size > 1:
      self.extractMin()
    self.__size = size
  def heapify(self):
    for i in range(self.__size // 2 - 1, -1, -1):
      self.sink(i)

h1 = MinHeap(10)
h1.insert(8)
h1.insert(35)
h1.insert(3)
h1.printHeap()
h1.insert(9)
h1.insert(12)
h1.insert(25)
h1.insert(15)
h1.printHeap()
h1.insert(16)
h1.insert(20)
h1.insert(23)
h1.printHeap()
h1.insert(34)
h1.insert(29)
h1.extractMin()
h1.printHeap()
h1.extractMin()
h1.printHeap()
h1.sort()
h1.printHeap()

[ 3  8 35  0  0  0  0  0  0  0]
[ 3  8  9 12 15 25 35  0  0  0]
[ 3  8  9 12 15 16 20 23 25 35]
Heap is full. Cannot insert
Heap is full. Cannot insert
[ 8 12  9 23 15 16 20 35 25  3]
[ 9 12 16 23 15 25 20 35  8  3]
[35 25 23 20 16 15 12  9  8  3]


In [7]:
import numpy as np
class MaxHeap:
  def __init__(self, cap):
    self.__cap = cap
    self.__arr = np.zeros(cap, int)
    self.__size = 0
  def insert(self, val):
    if self.__size >= self.__cap:
      print('Heap is full. Cannot insert')
      return
    self.__arr[self.__size] = val
    self.__size += 1
    self.swim()
  def swim(self):
    idx = self.__size - 1
    while self.__arr[idx] > self.__arr[idx-2//2] and idx > 0:
      self.__arr[idx], self.__arr[idx-2//2] = self.__arr[idx-2//2], self.__arr[idx]
      idx = idx-2//2
  def printHeap(self):
    print(self.__arr)
  def extractMax(self):
    if self.__size == 0:
      print('Heap is empty')
      return
    max = self.__arr[0]
    self.__arr[0], self.__arr[self.__size-1] = self.__arr[self.__size-1], self.__arr[0]
    self.__size -= 1
    self.sink(0)
    return max
  def sink(self, idx):
    max = idx
    l = 2*idx + 1
    r = 2*idx + 2
    if r < self.__size and self.__arr[r] > self.__arr[max]:
      max = r
    if l < self.__size and self.__arr[l] > self.__arr[max]:
      max = l
    if max != idx:
      self.__arr[max], self.__arr[idx] = self.__arr[idx], self.__arr[max]
      self.sink(max)
  def sort(self):
    self.heapify()
    size = self.__size
    while self.__size > 1:
      self.extractMax()
    self.__size = size
  def heapify(self):
    for i in range(self.__size//2 - 1, -1, -1):
      self.sink(i)

h2 = MaxHeap(10)
h2.insert(8)
h2.insert(35)
h2.insert(3)
h2.printHeap()
h2.extractMax()
h2.extractMax()
h2.extractMax()
h2.extractMax()
h2.insert(9)
h2.insert(22)
h2.insert(12)
h2.insert(25)
h2.insert(15)
h2.printHeap()
h2.insert(16)
h2.insert(20)
h2.insert(23)
h2.printHeap()
h2.insert(34)
h2.insert(29)
h2.extractMax()
h2.printHeap()
h2.extractMax()
h2.printHeap()
h2.sort()
h2.printHeap()

[35  8  3  0  0  0  0  0  0  0]
Heap is empty
[25 22 15 12  9  0  0  0  0  0]
[25 23 22 20 16 15 12  9  0  0]
[29 23 25 15 22 20 16  9 12 34]
[25 23 20 15 22 12 16  9 29 34]
[ 9 12 15 16 20 22 23 25 29 34]


In [ ]:
import numpy as np
def processTime(arr, m):
  h3 = MinHeap(m)
  for i in range(m):
    h3.insert(0)
  for i in arr:
    h3.insert(h3.extractMin() + i)
  h3.printHeap()

processTime([2, 4, 7, 1, 6], 4)

[2 4 7 7]


In [ ]:
def top_k_largest(arr, k):
  h4 = MaxHeap(len(arr))
  final = np.zeros(k, int)
  for i in arr:
    h4.insert(i)
  for i in range(k):
    final[i] = h4.extractMax()
  print(final)

top_k_largest([4, 10, 2, 8, 6, 7], 3)

[10  8  7]
