In [ ]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)
a = np.zeros(len(arr), dtype=int)
i = len(arr)-1
count = 0
while i>=0:
    print(arr[i])
    a[count] = arr[i]
    i -= 1
    count += 1
print(a)

[10 20 30 40 50]
50
40
30
20
10
[50 40 30 20 10]


In [ ]:
# right shift
arr = np.array([10, 20, 30, 40, 50])
n = int(input())
count = 0
while count<n:
    i = len(arr)-1
    while i>0:
        arr[i] = arr[i-1]
        i-=1
    arr[i] = 0
    count+=1
    print(arr)

2
[ 0 10 20 30 40]
[ 0  0 10 20 30]


In [ ]:
# left shift
arr = np.array([10, 20, 30, 40, 50])
n = int(input())
count = 0
while count<n:
    i = 0
    while i<len(arr)-1:
        arr[i] = arr[i+1]
        i+=1
    arr[i] = 0
    count+=1
    print(arr)

2
[20 30 40 50  0]
[30 40 50  0  0]


In [ ]:
# right rotate
arr = np.array([10, 20, 30, 40, 50])
n = int(input())
count = 0
while count<n:
    i = len(arr)-1
    x = arr[i]
    while i>0:
        arr[i] = arr[i-1]
        i-=1
    arr[i] = x
    count+=1
    print(arr)

2
[50 10 20 30 40]
[40 50 10 20 30]


In [ ]:
# left rotate
arr = np.array([10, 20, 30, 40, 50])
n = int(input())
count = 0
while count<n:
    i = 0
    x = arr[i]
    while i<len(arr)-1:
        arr[i] = arr[i+1]
        i+=1
    arr[i] = x
    count+=1
    print(arr)

2
[20 30 40 50 10]
[30 40 50 10 20]
