In [2]:
import numpy as np

In [ ]:
class Node:
  def __init__(self, ng, next = None):
    self.ng = ng
    self.next = next

# Undirected

In [ ]:
class matGraph:
  def __init__(self, vertices, edges = [], weight = 1):
    self.vertices = vertices
    self.matrix = np.zeros((len(vertices), len(vertices)), dtype = int)
    self.edges = edges
    self.addedges(edges, weight)

  def addedges(self, edges, weight = 1):
    if len(edges[0]) != 3:
      for edge in edges:
        self.matrix[edge[0]][edge[1]] = weight
        self.matrix[edge[1]][edge[0]] = weight
    else:
      for edge in edges:
        self.matrix[edge[0]][edge[1]] = edge[2]
        self.matrix[edge[1]][edge[0]] = edge[2]
    return self.matrix

  def maxdegree(self):
    max_degree = 0
    vertex = -1
    for ver in range(len(self.matrix)):
      degree = 0
      for neighbor in range(len(self.matrix)):
        if self.matrix[ver][neighbor] != 0:
          degree += 1
      if degree > max_degree:
        max_degree = degree
        vertex = ver
    return vertex, max_degree

  def edgeweight(self):
    max_wei = 0
    vertex = -1
    for ver in range(len(self.matrix)):
      wei = 0
      for neighbor in range(len(self.matrix)):
        if self.matrix[ver][neighbor] != 0:
          wei += self.matrix[ver][neighbor]
      if wei > max_wei:
        max_wei = wei
        vertex = ver
    return vertex, max_wei


class linkGraph:
  def __init__(self, vertices, edges [], weight = 1):
    self.vertices = vertices
    self.li = Node(vertices[0])
    self.lihead = self.li
    for i in vertices[1:]:
      self.li.next = Node(i)
      self.li = self.li.next
    self.edges = edges
    self.addedges(edges, weight)

  def addedges(self, edges, weight = 1)
    if len(edges[0]) != 3:

    return self.matrix

# Directed

In [ ]:
class mat2Graph:
  def __init__(self, vertices, edges, weight = 1):
    self.vertices = vertices
    self.matrix = np.zeros((len(vertices), len(vertices)), dtype = int)
    self.edges = edges
    self.addedges(edges, weight)
    self.weight = weight

  def addedges(self, edges, weight = 1):
    if len(edges[0]) != 3:
      for edge in edges:
        self.matrix[edge[0]][edge[1]] = weight
    else:
      for edge in edges:
        self.matrix[edge[0]][edge[1]] = edge[2]
    return self.matrix

  def maxdegree(self):
    max_degree = 0
    vertex = -1
    for ver in range(len(self.matrix)):
      degree = 0
      for neighbor in range(len(self.matrix)):
        if self.matrix[ver][neighbor] != 0:
          degree += 1
      if degree > max_degree:
        max_degree = degree
        vertex = ver
    return vertex, max_degree

  def edgeweight(self):
    max_wei = 0
    vertex = -1
    for ver in range(len(self.matrix)):
      wei = 0
      for neighbor in range(len(self.matrix)):
        if self.matrix[ver][neighbor] != 0:
          wei += self.matrix[ver][neighbor]
      if wei > max_wei:
        max_wei = wei
        vertex = ver
    return vertex, max_wei

  def unwei(self):
    for ver in range(len(self.matrix)):
      for j in range(len(self.matrix)):
        if self.matrix[ver][j] != 0:
          self.matrix[ver][j] = 1
          self.matrix[j][ver] = 1
    return self.matrix

# Task 1

In [26]:
#Driver code Matrix
vertices = [0,1,2,3,4,5,6]
edges = [(0,1), (0,3), (0,6),
(1, 2), (1, 3), (1, 4),
(2, 5),
(3, 4), (3,6),
(4,0),
(5, 1), (5,3), (5,4),
(6, 1) , (6,0)]

graph = matGraph(vertices, edges)
print(graph.matrix)
print("----------------------")
print(graph.maxdegree())

[[0 1 0 1 1 0 1]
 [1 0 1 1 1 1 1]
 [0 1 0 0 0 1 0]
 [1 1 0 0 1 1 1]
 [1 1 0 1 0 1 0]
 [0 1 1 1 1 0 0]
 [1 1 0 1 0 0 0]]
----------------------
(1, 6)


# Task 2

In [23]:
#Driver code Matrix
vertices = [0,1,2,3,4,5,6]
edges = [(0, 1, 4), (0, 3, 7), (0, 6, 2),
(1, 2, 3), (1, 3, 2), (1, 4, 9),
(2, 5, 8),
(3, 4, 11), (3,6, 5),
(4, 0, 12),
(5, 1, 18), (5, 3, 10), (5, 4, 13),
(6, 1, 19) , (6, 0, 2)]
graph2 = matGraph(vertices, edges)
print(graph2.matrix)
print("----------------------")
print(graph2.edgeweight())

[[ 0  4  0  7 12  0  2]
 [ 4  0  3  2  9 18 19]
 [ 0  3  0  0  0  8  0]
 [ 7  2  0  0 11 10  5]
 [12  9  0 11  0 13  0]
 [ 0 18  8 10 13  0  0]
 [ 2 19  0  5  0  0  0]]
----------------------
(1, 55)


# Task 3

In [30]:
#Driver code Matrix
vertices = [0,1,2,3,4,5,6]
edges = [(0,1), (0,3), (0,6),
(1, 2), (1, 3), (1, 4),
(2, 5),
(3, 4), (3,6),
(4,0),
(5, 1), (5,3), (5,4),
(6, 1) , (6,0)]

graph3 = mat2Graph(vertices, edges)
print(graph3.matrix)
print("----------------------")
print(graph3.maxdegree())

print("======================")

vertices = [0,1,2,3,4,5,6]
edges = [(0, 1, 4), (0, 3, 7), (0, 6, 2),
(1, 2, 3), (1, 3, 2), (1, 4, 9),
(2, 5, 8),
(3, 4, 11), (3,6, 5),
(4, 0, 12),
(5, 1, 18), (5, 3, 10), (5, 4, 13),
(6, 1, 19) , (6, 0, 2)]
graph4 = mat2Graph(vertices, edges)
print(graph4.matrix)
print("----------------------")
print(graph4.edgeweight())

[[0 1 0 1 0 0 1]
 [0 0 1 1 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 0 1]
 [1 0 0 0 0 0 0]
 [0 1 0 1 1 0 0]
 [1 1 0 0 0 0 0]]
----------------------
(0, 3)
[[ 0  4  0  7  0  0  2]
 [ 0  0  3  2  9  0  0]
 [ 0  0  0  0  0  8  0]
 [ 0  0  0  0 11  0  5]
 [12  0  0  0  0  0  0]
 [ 0 18  0 10 13  0  0]
 [ 2 19  0  0  0  0  0]]
----------------------
(5, 41)


# Task 4

In [31]:
#Driver code Matrix
vertices = [0,1,2,3,4,5,6]
edges = [(0, 1, 4), (0, 3, 7), (0, 6, 2),
(1, 2, 3), (1, 3, 2), (1, 4, 9),
(2, 5, 8),
(3, 4, 11), (3,6, 5),
(4, 0, 12),
(5, 1, 18), (5, 3, 10), (5, 4, 13),
(6, 1, 19) , (6, 0, 2)]
graph5 = mat2Graph(vertices, edges)
print(graph5.matrix)
print("----------------------")
print(graph5.unwei())

[[ 0  4  0  7  0  0  2]
 [ 0  0  3  2  9  0  0]
 [ 0  0  0  0  0  8  0]
 [ 0  0  0  0 11  0  5]
 [12  0  0  0  0  0  0]
 [ 0 18  0 10 13  0  0]
 [ 2 19  0  0  0  0  0]]
----------------------
[[0 1 0 1 1 0 1]
 [1 0 1 1 1 1 1]
 [0 1 0 0 0 1 0]
 [1 1 0 0 1 1 1]
 [1 1 0 1 0 1 0]
 [0 1 1 1 1 0 0]
 [1 1 0 1 0 0 0]]
